spring:
  application:
    name: checkout-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/db/checkoutdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  sql:
    init:
      data-locations: classpath:data/price_data.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
